site_name: Oslo Pust Wiki
site_description: Internal documentation for Oslo Pust
site_author: Oslo Pust Team
site_url: https://tiniusweb2.github.io/oslopust/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tabs.sticky
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  - search
  - git-revision-date
  - git-authors
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes

extra_javascript:
  - javascripts/mermaid.js

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 Oslo Pust
nav:
  - Home: index.md
  - Test: test.md
  - Business:
    - Overview: business/index.md
    - Business Plan: business/business-plan.md
  - Products:
    - Overview: products/index.md
    - Specifications: products/product-supplier-specs.md
  - Operations:
    - Overview: operations/index.md
    - Suppliers: operations/suppliers-guide.md
  - Team:
    - Overview: team/index.md
    - Roles: team/roles.md
  - Resources:
    - Overview: resources/index.md
