site_name: Oslo Pust Wiki
site_description: Internal documentation for Oslo Pust
site_author: Oslo Pust Team
site_url: https://tiniusweb2.github.io/oslopust/

# Theme configuration
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.expand
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - announce.dismiss

# Advanced plugins
plugins:
  - search
  - git-revision-date
  - git-authors
  - glightbox
  - macros
  - rss:
      abstract_chars_count: 160
      date_from_meta:
        as_creation: "date"
        as_update: "update"
      feed_ttl: 1440
  - with-pdf:
      author: Oslo Pust Team
      copyright: Copyright © 2024 Oslo Pust
      cover_subtitle: Internal Documentation
      toc_level: 3
      output_path: pdf/documentation.pdf
      custom_template_path: docs/assets/templates
  - swagger-ui-tag

# Extended markdown features
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - def_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - abbr
  - attr_list
  - def_list

# Extra features
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tiniusweb2
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  version:
    provider: mike
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  status:
    new: Recently added
    deprecated: Deprecated
    beta: Beta

# Add versioning
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - assets/javascripts/tables.js
  - assets/javascripts/feedback.js

extra_css:
  - assets/stylesheets/extra.css

# Copyright
copyright: Copyright &copy; 2024 Oslo Pust
