site_name: Oslo Pust Wiki
site_description: Internal documentation for Oslo Pust
site_author: Oslo Pust Team

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - toc.follow

nav:
  - Overview: 
    - Project: index.md
    - Business Plan: business-plan.md
    - Competitors: competitors.md
  - Products:
    - Specifications: specifications/product-supplier-specs.md
    - Supplier Guide: suppliers-guide.md
  - Team:
    - Roles & Structure: roles.md
  - Resources:
    - Tools & Links: resources.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - def_list
  - footnotes

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.6.1/mermaid.min.js

copyright: Copyright &copy; 2024 Oslo Pust
