name: Versioning
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mike
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mike deploy --push --update-aliases ${GITHUB_REF#refs/tags/v} latest
